import os
import re
import json
import logging
from typing import List, Dict, Any
from backend.services.storage import get_all_tracks, save_all_tracks
from backend.services.ytmusic_sync import YTMusicSyncService

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("dance_playlists_builder")

def sync_custom_playlist(yt: YTMusicSyncService, title: str, description: str, tracks: List[Any]) -> Dict[str, Any]:
    logger.info(f"\n==========================================")
    logger.info(f"Building Playlist: '{title}' ({len(tracks)} tracks)")
    logger.info(f"==========================================")

    if not tracks:
        logger.warning(f"No tracks found for playlist '{title}'. Skipping.")
        return {"title": title, "count": 0, "url": None}

    playlist_id = yt.create_or_get_playlist(title, description)
    logger.info(f"Created/found playlist '{title}' with ID: {playlist_id}")

    video_ids = []
    for idx, t in enumerate(tracks):
        v_id = t.matched_yt_id
        if not v_id:
            match = yt.search_best_match(t)
            if match and match[0]:
                v_id = match[0]
                t.matched_yt_id = match[0]
                t.matched_yt_title = match[1]
                t.is_synced = True

        if v_id:
            video_ids.append(v_id)

    if video_ids:
        # Batch add in chunks of 50
        for i in range(0, len(video_ids), 50):
            try:
                yt.add_playlist_items(playlist_id, video_ids[i:i+50])
                logger.info(f"Pushed batch {i+1}-{min(i+50, len(video_ids))} to '{title}'")
            except Exception as e:
                logger.error(f"Error adding batch to '{title}': {e}")

    playlist_url = f"https://music.youtube.com/playlist?list={playlist_id}"
    return {
        "title": title,
        "playlist_id": playlist_id,
        "playlist_url": playlist_url,
        "total_songs": len(video_ids)
    }

def main():
    all_tracks = get_all_tracks()
    logger.info(f"Loaded {len(all_tracks)} total tracks from library.")

    yt = YTMusicSyncService()
    if not yt.is_authenticated():
        logger.error("YouTube Music is not authenticated. Please connect in Settings.")
        return

    # 1. Breakbeat
    breakbeat_tracks = [
        t for t in all_tracks 
        if t.sub_genre and 'breakbeat' in t.sub_genre.lower()
    ]

    # 2. Funk
    funk_tracks = [
        t for t in all_tracks 
        if t.sub_genre and any(k in t.sub_genre.lower() for k in [
            'funk', 'baile funk', 'brazilian funk', 'funk carioca', 'funkot', 
            'future funk', 'jazz-funk', 'synth-funk', 'funky house'
        ])
    ]

    # 3. Breakcore
    breakcore_tracks = [
        t for t in all_tracks 
        if t.sub_genre and 'breakcore' in t.sub_genre.lower()
    ]

    # 4. Rave & High Energy (Techno, Hardstyle, Rave, Hardcore, Jumpstyle, Frenchcore, Eurodance, Club, Trance, Hard Dance)
    rave_subgenres = [
        'techno', 'hardstyle', 'hard dance', 'hardcore techno', 'hardcore', 
        'jumpstyle', 'frenchcore', 'hard techno', 'industrial techno', 
        'melodic techno', 'eurodance', 'club', 'jersey club', 'deconstructed club', 
        'nightcore', 'trance', 'psytrance', 'dance', 'edm'
    ]

    def is_rave_track(t):
        if not t.sub_genre: return False
        sg = t.sub_genre.lower()
        if 'breakbeat' in sg or 'funk' in sg or 'breakcore' in sg or 'rock' in sg or 'metal' in sg or 'hip-hop' in sg or 'punk' in sg:
            return False
        return any(k in sg for k in rave_subgenres)

    rave_tracks = [t for t in all_tracks if is_rave_track(t)]

    results = []

    # Sync Playlist 1: Rave & High Energy
    r1 = sync_custom_playlist(
        yt,
        title="Rave & High Energy (Techno / Hardstyle)",
        description=f"High Energy Dance, Techno, Hardstyle, Jumpstyle, Trance & Rave curated by SoundSort AI ({len(rave_tracks)} tracks)",
        tracks=rave_tracks
    )
    results.append(r1)

    # Sync Playlist 2: Breakbeat
    r2 = sync_custom_playlist(
        yt,
        title="Breakbeat",
        description=f"Curated Breakbeat collection generated by SoundSort AI ({len(breakbeat_tracks)} tracks)",
        tracks=breakbeat_tracks
    )
    results.append(r2)

    # Sync Playlist 3: Funk
    r3 = sync_custom_playlist(
        yt,
        title="Funk & Brazilian Funk",
        description=f"Curated Funk, Baile Funk, Brazilian Funk & Funkot created by SoundSort AI ({len(funk_tracks)} tracks)",
        tracks=funk_tracks
    )
    results.append(r3)

    # Sync Playlist 4: Breakcore
    r4 = sync_custom_playlist(
        yt,
        title="Breakcore",
        description=f"Curated Breakcore playlist created by SoundSort AI ({len(breakcore_tracks)} tracks)",
        tracks=breakcore_tracks
    )
    results.append(r4)

    save_all_tracks(all_tracks)

    # Summary
    logger.info("\n==========================================")
    logger.info("🎉 ALL 4 PLAYLISTS CREATED & SYNCED!")
    logger.info("==========================================")
    for r in results:
        logger.info(f"- {r['title']}: {r['total_songs']} songs -> {r['playlist_url']}")

if __name__ == "__main__":
    main()
